# Generated by Django 4.2.5 on 2023-09-12 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='account_type',
            field=models.CharField(default='Asset', max_length=200),
        ),
        migrations.AddField(
            model_name='account',
            name='remarks',
            field=models.CharField(default='', max_length=200),
        ),
    ]
