# Generated by Django 4.2.6 on 2023-10-05 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop3_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attn_number', models.CharField(max_length=20)),
                ('movie_name', models.CharField(max_length=20)),
                ('seat_number', models.CharField(max_length=10)),
                ('show_time', models.CharField(max_length=20)),
                ('created_by', models.CharField(default='Auto', max_length=30)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(default='Auto', max_length=30)),
                ('void', models.CharField(choices=[('0', '0'), ('1', '1')], default='0', max_length=1)),
            ],
            options={
                'ordering': ['-created_time'],
            },
        ),
    ]
